portal_main_page_homepage:
    path:     /
    defaults: { _controller: PortalMainPageBundle:Default:index }

portal_main_page_update:
    path:     /update
    defaults: { _controller: PortalMainPageBundle:Default:update }

portal_main_page_test:
    path:     /test
    defaults: { _controller: PortalMainPageBundle:Default:test }
portal_main_page_kino:
    path:     /kino
    defaults: { _controller: PortalMainPageBundle:Default:kino }
portal_main_page_posters:
    path:     /posters
    defaults: { _controller: PortalMainPageBundle:Default:posters }
portal_main_page_world:
    path:     /world
    defaults: { _controller: PortalMainPageBundle:Default:world }
portal_main_page_idKinopoisk:
    path:     /idKinopoisk
    defaults: { _controller: PortalMainPageBundle:Default:idKinopoisk }
portal_main_page_getInfo:
    path:     /getInfo
    defaults: { _controller: PortalMainPageBundle:Default:getInfo }